USE [SoftCredito]
GO
/****** Object:  StoredProcedure [dbo].[sp_appv1_mp_referencias]    Script Date: 08/09/2021 08:08:08 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- CREATE PROC sp_appv1_mp_referencias 
ALTER PROC [dbo].[sp_appv1_mp_referencias]
	@CLAVE_SOLICITUD VARCHAR(50)
AS

DECLARE @TABLE TABLE (
	REF_CONEKTA VARCHAR(50),
	REF_OPENPAY VARCHAR(50),
	REF_WILLYS VARCHAR(50),
	TIENE_REF_CONEKTA INTEGER,
	TIENE_REF_OPENPAY INTEGER,
	TIENE_REF_WILLYS INTEGER
)

INSERT INTO @TABLE VALUES('99000002769992', '','',1,0,0)

SELECT * FROM @TABLE;